# Build information
ifneq ($(EV_PRODUCT_BUILD),)
PRODUCT_BUILD := $(EV_PRODUCT_BUILD)
endif
PRODUCT_BUILD ?= userbuild

# Package name
ifneq ($(SKIP_VERBOSE_DATE),true)
TARGET_OTA_PACKAGE_NAME := $(TARGET_PRODUCT)-$(PLATFORM_VERSION)-$(PRODUCT_BUILD)-$(BUILD_DATETIME_FROM_FILE)
endif
TARGET_OTA_PACKAGE_NAME ?= $(TARGET_PRODUCT)-$(PLATFORM_VERSION)-$(PRODUCT_BUILD)
